### ISSUE TITLE
Separate build assets from source assets

### ISSUE THREAD

**Issue by farooqkz** [b-simjoo/VonNeumannEmulator#2]
I don't think it's a good idea for a web app to have them both in one branch or place. Even though many do this including a friend of mine(looking at you @strukturart !). So my idea is that if it is going to be run somewhere, you include the build assets in a packaged file in Releases. If not, which is your case, deploy them to another branch, in this case `gh-pages` and tell Github Pages to serve from there. Something similar to my personal blog.

**Comment by b-simjoo** [comment]
Actually, I was thinking about the same things myself, but the project is not so big that there is a need for such work in my opinion.

**Comment by farooqkz** [comment]
As you wish. Remember to close this issue as "Invalid" not "Completed". This is GH's new feature :)
